if (MAVLINK_INCLUDE_DIR AND MAVLINK_LIBRARIES)
  # Already in cache, be silent
  set(MAVLINK_FIND_QUIETLY TRUE)
endif (MAVLINK_INCLUDE_DIR AND MAVLINK_LIBRARIES)

find_path(MAVLINK_INCLUDE_DIR mavlink/v2.0/message.hpp)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(MAVLINK DEFAULT_MSG MAVLINK_INCLUDE_DIR)

mark_as_advanced(MAVLINK_INCLUDE_DIR)
