using YAML

struct InvalidInterfaceError <: Exception
var::String
end

# turns Julia/Protobuf scoping (".") into C++ scoping ("::")
function to_cpp_scoping(s::String)
    occursin("::", s) ? s : replace(s, "." => "::")
end

#function remove_namespaces(s::String)
#    last(split(s, "::"))
#end

function check_required_keys(required_keys, prefix::String, yaml)
    for key in required_keys
        if !haskey(yaml, key)
            throw(InvalidInterfaceError("Interface file must have '$(prefix).$(key)' key"))
        end
    end
end

function check_scheme(scheme)
    if scheme != "PROTOBUF"
        throw(InvalidInterfaceError("The only supported scheme is currently 'PROTOBUF'"))
    end
end


function collect_layer(layer::String, layer_yaml)
    publish = Vector{String}()
    subscribe = Vector{String}()
    layer_function=haskey(layer_yaml, "alias") ? layer_yaml["alias"] : layer
    layer_enum=uppercase(layer)

    required_keys = (["group", "scheme", "type"])
    if haskey(layer_yaml, "publishes")
        for p in layer_yaml["publishes"]
            check_required_keys(required_keys, "$(layer).publishes", p)
            check_scheme(p["scheme"])
            # Julia ::Method sig does not include scoping, so we need to remove it here
            t = to_cpp_scoping(p["type"])
            push!(publish, "GOBY_JULIA_IF_PUBLICATION($(p["scheme"]), $(layer_enum), $(layer_function), $(p["group"]), $(t))")
        end
    end
    
    if haskey(layer_yaml, "subscribes")
        for s in layer_yaml["subscribes"]
            check_required_keys(required_keys, "$(layer).subscribes", s)
            check_scheme(s["scheme"])
            t = to_cpp_scoping(s["type"])
            push!(subscribe, "GOBY_JULIA_IF_SUBSCRIPTION($(s["scheme"]), $(layer_enum), $(layer_function), $(s["group"]), $(t))")
        end
    end
        
    return (publish, subscribe)
end


function gen_includes(io_out::IOStream, includes)
    write(io_out, "#include <goby/middleware/languages/julia/application.h>\n\n")

    for include in includes
        write(io_out, "#include \"$(include)\"\n")
    end
    
    write(io_out, "\n")
end

function gen_application_macros(io_out::IOStream, application_yaml)
    check_required_keys(("name", "cpp_type", "config"), "application", application_yaml)
    config_yaml = application_yaml["config"]
    check_required_keys(("scheme", "type"), "application.config", config_yaml)
    check_scheme(config_yaml["scheme"])

    c = to_cpp_scoping(config_yaml["type"])
    write(io_out, "#define CONFIG_TYPE $(c)\n")
    t = to_cpp_scoping(application_yaml["cpp_type"])
    write(io_out, "#define APPLICATION_TYPE $(t)<CONFIG_TYPE>\n")
    write(io_out, "#define APPLICATION_NAME $(application_yaml["name"])\n")
    write(io_out, "\n")
end

function gen_class(io_out::IOStream, application_name::String,
                   publish::Vector{String}, subscribe::Vector{String})
    write(io_out, """\
class APPLICATION_NAME : public goby::middleware::julia::Application<APPLICATION_TYPE>
{
  public:
    void publish(goby::middleware::julia::Identifier id, const std::vector<char>& bytes)
    {
""")

    for p in publish
        write(io_out, "        "*p*"\n")
    end
        
    write(io_out, """\

        GOBY_JULIA_FAIL("publish")
    }

    void subscribe(goby::middleware::julia::Identifier id, std::string func, std::string module)
    {
""")
    
    for s in subscribe
        write(io_out, "        "*s*"\n")
    end

    write(io_out, """\

        GOBY_JULIA_FAIL("subscribe")
    }
};

GOBY_JULIA_DEFINE_MODULE(APPLICATION_NAME)
""")
end

function goby_gen_cpp(in_yaml::String, out_cpp::String, includes)

    println("Generating $(out_cpp) from $(in_yaml)")
    
    interface_yaml = YAML.load_file(in_yaml)
    
    io_out::IOStream = open(out_cpp, "w");
    write(io_out, """\
// ########################
// #   Goby <--> Julia    #
// #  C++ support library #
// ########################
// This file was autogenerated from
// $(in_yaml)
""")
    gen_includes(io_out, includes)
    gen_application_macros(io_out, interface_yaml["application"])

    layers = ("interthread", "interprocess", "intermodule")
    publish = Vector{String}()
    subscribe = Vector{String}()
    for layer in layers
        if haskey(interface_yaml, layer)
            p, s = collect_layer(layer, interface_yaml[layer])
            append!(publish, p)
            append!(subscribe, s)
        end
    end
    gen_class(io_out, interface_yaml["application"]["name"], publish, subscribe)
end
