syntax = "proto2";
import "goby/middleware/protobuf/app_config.proto";
import "goby/zeromq/protobuf/interprocess_config.proto";

package goby.test.julia.protobuf;

message TestConfig
{
    optional goby.middleware.protobuf.AppConfig app = 1;
    optional goby.zeromq.protobuf.InterProcessPortalConfig interprocess = 2;

    optional int32 num_messages = 3 [default = 10];
}

message CommsTx
{
    optional int32 request_id = 1;
}

message CommsRx
{
    optional int32 request_id = 1;
    optional string payload = 2;
}
